# Generated by Django 5.2.1 on 2025-10-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comments_author_alter_comments_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='mediafile',
            field=models.FileField(blank=True, null=True, upload_to='posts/media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='mediatype',
            field=models.CharField(blank=True, choices=[('Image', 'Фото'), ('Video', 'Видео')]),
        ),
    ]
