# Generated by Django 5.2.1 on 2025-10-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
        ('posts', '0003_remove_post_image_remove_post_video_post_mediafile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userposts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post'),
        ),
    ]
